# Generated by Django 2.2.15 on 2020-09-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readdetail',
            old_name='dete',
            new_name='date',
        ),
    ]
