# Generated by Django 2.2.15 on 2020-09-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200923_0527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
